#!/bin/bash
# EMAIL FIX - Quick Setup Script

echo "🔧 Email Credentials Fix Applied"
echo "=================================="
echo ""
echo "✅ File Updated: controller/ClientsApi_v2.js"
echo "   - Line 320: Fixed viewer email in client creation"
echo "   - Line 728: Fixed viewer email in create-viewer endpoint"
echo ""
echo "📋 What was fixed:"
echo "   • emailService.sendCredentials() is now properly awaited"
echo "   • Email sending errors are now logged"
echo "   • Viewer credentials guaranteed to send before response"
echo ""
echo "🔑 Next Steps:"
echo ""
echo "1. Configure SMTP in .env file:"
echo "   SMTP_HOST=smtp.gmail.com"
echo "   SMTP_PORT=587"
echo "   SMTP_USER=your-email@gmail.com"
echo "   SMTP_PASS=your-app-password"
echo "   SMTP_SECURE=false"
echo "   SMTP_FROM=your-email@gmail.com"
echo ""
echo "2. Restart server:"
echo "   npm start"
echo ""
echo "3. Test by creating a client with viewer:"
echo "   POST /api/clients"
echo "   with 'createViewer': true"
echo ""
echo "4. Check logs for: 'Viewer credentials sent to ... Success'"
echo ""
echo "📚 Documentation:"
echo "   - EMAIL_FIX_GUIDE.md (Detailed troubleshooting)"
echo "   - EMAIL_FIX_SUMMARY.txt (Quick summary)"
echo ""
echo "✨ Done! Emails should now send correctly."
